default_language_version:
  python: python3.8
exclude: ^.stubs/
repos:
  - repo: https://github.com/psf/black
    # The `refs/tags/<tag>:refs/tags/<tag>` is needed for black's required-version to work:
    # https://github.com/psf/black/issues/2493#issuecomment-1081987650
    rev: 'refs/tags/22.3.0:refs/tags/22.3.0'
    hooks:
      - id: black
  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker
    rev: '1.0.1'
    hooks:
      - id: black-disable-checker
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: infogen
        name: infogen
        description: >-
          Script to automatically generate info.json files and generate class docstrings
          from single info.yaml file for whole repo.
        entry: python ./.tools/infogen.py
        language: python
        additional_dependencies:
          # a bit much since we only need VersionInfo but it's the least hacky solution
          - Red-DiscordBot
          - pathspec~=0.9.0
          - parso~=0.8.3
          - strictyaml==1.6.1
          - tomli>=2.0.1,<3
        verbose: true
        always_run: true
        pass_filenames: false
        require_serial: true
  # ideally, we should also run mypy here, but mypy isn't exactly file-based
  # which could cause some issues.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # `.gitattributes` should technically already handle this
      # but autocrlf can result in local files keeping the CRLF
      # which is problematic for codespell
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"

      # Trailing whitespace is evil
      - id: trailing-whitespace

      # Require literal syntax when initializing builtin types
      - id: check-builtin-literals

      # Ensure that links to code on GitHub use the permalinks
      - id: check-vcs-permalinks

      # Syntax validation
      - id: check-ast
      - id: check-json
      - id: check-toml
      # can be switched to yamllint when this issue gets resolved:
      # https://github.com/adrienverge/yamllint/issues/238
      - id: check-yaml

      # JSON auto-formatter
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"

      # Checks for git-related issues
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        additional_dependencies: ['.[hard-encoding-detection]']
        args:
          - "-C=1"
          - "--hard-encoding-detection"
