[tool.black]
target-version = ['py38']
required-version = '22.3.0'
force-exclude = '''
/(
    \.stubs
)/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
skip_glob = [
    ".stubs/*",
]
filter_files = true
