name: black

on:
  - push
  - pull_request

jobs:
  black:
    name: Style check with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.7"
      - run: python -m pip install -U black
        name: Install Black
      - run: black --check --target-version py37 ./
        name: Style check with Black
