name: black

on:
  - push
  - pull_request

jobs:
  black:
    name: Style check with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache pip requirements
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashfiles('.ci/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Black
        run: python -m pip install -U black
      - name: Style check with Black
        run: black --check --target-version py37 ./
