name: compile_all

on:
  - push
  - pull_request

jobs:
  compile_all:
    name: Compile all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
        include:
          - python-version: "3.8"
            py-version: "py38"
    env:
      PYTHON: python${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Cache pip requirements
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.PYTHON }}-pip-${{ hashfiles('.ci/**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install --user -Ur .ci/requirements/tools.txt
          python -m pip install --user -Ur .ci/${{ matrix.py-version }}/requirements/all_cogs.txt
      - name: Compile all
        run: |
          DIRS=$( cat .ci/${{ matrix.py-version }}/compileall_file_list.txt )
          echo python -m compileall $DIRS
          python -m compileall $DIRS
