name: compile_all

on:
  - push
  - pull_request

jobs:
  compile_all:
    name: Compile all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
    steps:
      - uses: actions/checkout@v1
      - name: Cache pip requirements
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python${{ matrix.python-version }}-pip-${{ hashfiles('.ci/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-python${{ matrix.python-version }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt install --yes python${{ matrix.python-version }} \
          python${{ matrix.python-version }}-dev python3-pip build-essential
      - name: Install requirements
        run: |
          python${{ matrix.python-version }} -m pip install -U pip setuptools wheel
          python${{ matrix.python-version }} -m pip install --user -Ur .ci/requirements/tests.txt
      - name: Compile all
        run: >
          python${{ matrix.python-version }} -m compileall
          ${ python${{ matrix.python-version }} .ci/list_files.py }
