name: flake8

on:
  - push
  - pull_request

jobs:
  flake8:
    name: Lint with Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install --user -Ur .ci/requirements/lint.txt
      - name: Lint with Flake8
        run: python -m flake8
