name: infogen

on:
  - push
  - pull_request

jobs:
  infogen:
    name: Check for problems with infogen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install --user -U Red-DiscordBot
          python -m pip install --user -Ur .ci/requirements/tools.txt
      - name: Check for problems with infogen
        run: python .tools/infogen.py --diff
